In [1]:
import os.path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data_dir = 'data/'
maint = pd.read_csv(os.path.join(data_dir, 'maint.csv'), parse_dates=['datetime'])

In [3]:
machineIDs = np.unique(maint['machineID'].values)
comps = np.unique(maint['comp'].values)
begin_time = maint['datetime'].min()
end_time =  maint['datetime'].max()

In [4]:
times_list = list()
fails_list = list()
for machine in machineIDs:
    machine_fail_list = list()
    machine_list = list()
    for comp in comps:
        aux_list = [begin_time]+list(maint[maint['machineID'] == machine][maint['comp'] == comp]['datetime'])+[end_time]
        aux_fail_list = list(maint[maint['machineID'] == machine][maint['comp'] == comp]['IF_FAIL'])+[0]
        machine_list.append(aux_list)
        machine_fail_list.append(aux_fail_list)
    times_list.append(machine_list)
    fails_list.append(machine_fail_list)

C:\Users\sergiojesus\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys
C:\Users\sergiojesus\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [5]:
incomp_times_list = list()
comp_times_list = list()
for i, machine in enumerate(times_list):
    incomp_machine_list = list()
    comp_machine_list = list()
    for j, failure in enumerate(machine):
        incomp_failure_list = list()
        comp_failure_list = list()
        for index in range(len(failure)-1):
            if fails_list[i][j][index] == 0:
                incomp_failure_list.append((failure[index+1]-failure[index]).days)
            elif fails_list[i][j][index] == 1:
                comp_failure_list.append((failure[index+1]-failure[index]).days)
        incomp_machine_list.append(incomp_failure_list)
        comp_machine_list.append(comp_failure_list)
    incomp_times_list.append(incomp_machine_list)
    comp_times_list.append(comp_machine_list)

In [10]:
incomp_times_frame = pd.DataFrame(data=np.array(incomp_times_list), columns=comps, index=machineIDs)
comp_times_frame = pd.DataFrame(data=np.array(comp_times_list), columns=comps, index=machineIDs)

In [11]:
incomp_times_frame

,comp1,comp2,comp3,comp4
1,"[105, 113, 15, 15, 15, 46]","[105, 15, 15, 90, 76]","[165, 15, 15, 30, 30, 15, 30, 30, 15, 30, 1]","[30, 15, 15, 16]"
2,"[30, 245, 15, 30, 15, 30, 64]","[165, 45, 45, 15, 109]","[135, 95, 60, 105, 30, 15, 15, 15, 45, 15, 15,...","[60, 200, 15, 75, 30, 15, 165, 19]"
3,"[0, 15, 255, 14]","[0, 15, 60, 15, 150, 15, 14]","[60, 175, 30, 60, 90, 15, 15, 45, 30, 15, 44]","[105, 145, 30, 30, 45, 105, 45, 45, 29]"
4,"[0, 269, 60, 105, 25]","[75, 45, 90, 40]","[30, 209, 15, 60, 90, 15, 105, 15, 15, 25]","[15, 224, 30, 15, 105, 75, 45, 60, 10]"
5,"[60, 189, 15, 30, 60, 30, 45, 15, 30, 30, 30]","[15, 204, 15, 75, 15, 15, 15, 15, 30, 15, 30, ...","[45, 30, 0]","[135, 84, 45, 30, 75, 45, 45, 60, 60]"
6,"[180, 72, 105, 45, 45, 15, 42]","[165, 177, 15, 90, 15, 45, 72]","[75, 162, 15, 75, 45, 45, 90, 45, 15, 12]","[45, 192, 75, 30, 30, 15, 45, 30, 30, 45, 30, 12]"
7,"[105, 30, 30, 15, 15, 124]","[150, 30, 15, 15, 15, 64]","[30, 215, 15, 15, 225, 45, 30, 4]","[105, 30, 30, 15, 19]"
8,"[180, 15, 15, 30, 60, 45, 30, 32]","[30, 30, 15, 15, 15, 75, 2]","[45, 292, 45, 15, 90, 45, 30, 17]","[195, 30, 122]"
9,"[60, 196, 90, 15, 30, 15, 30, 23]","[30, 271, 15, 75, 45, 45, 15, 23]","[75, 15, 15, 30, 15, 8]","[90, 136, 60, 75, 15, 90, 30, 83]"
10,"[150, 15, 30, 150, 30, 36]","[180, 93, 120, 15, 15, 15, 6]","[210, 30, 30, 30, 15, 21]","[75, 198, 60, 60, 30, 30, 30, 96]"
11,"[60, 15, 15, 75, 60, 30, 45, 15, 11]","[120, 30, 11]","[120, 118, 75, 45, 75, 15, 15, 30, 86]","[195, 58, 135, 165, 26]"
12,"[150, 30, 75, 15, 15, 45, 30, 23]","[180, 61, 15, 15, 15, 15, 15, 120, 15, 15, 15, 8]","[150, 23]","[135, 121, 180, 15, 15, 30, 75, 8]"
13,"[45, 225, 30, 75, 15, 60, 15, 114]","[30, 225, 15, 15, 90, 15, 15, 30, 9]","[135, 90, 15, 90, 15, 75, 15, 105, 30, 9]","[90, 15, 30, 15, 15, 24]"
14,"[75, 15, 15, 30, 30, 45, 121]","[90, 15, 15, 90, 15, 15, 15, 15, 15, 15, 15, 3...","[30, 203, 30, 15, 75, 195, 15, 16]","[210, 23, 60, 75, 120, 15, 15, 15, 45, 1]"
15,"[30, 30, 15, 30, 15, 30, 30, 15, 45, 15, 30, 1...","[165, 67, 135, 75, 75, 62]","[180, 127, 45, 30, 15, 60, 15, 90, 17]","[15, 15, 30, 2]"
16,"[150, 90, 15, 30, 15, 15, 15, 15, 55]","[210, 29, 105, 90, 15, 40]","[210, 44, 15, 30, 255, 25]","[180, 134, 15, 30, 15, 15, 60, 30, 30, 30, 15,..."
17,"[0, 236, 15, 15, 45, 60, 45, 163]","[105, 15, 15, 30, 45, 28]","[135, 131, 15, 15, 30, 15, 105, 15, 30, 45, 30...","[120, 30, 15, 15, 43]"
18,"[150, 69, 30, 30, 30, 45, 45]","[195, 69, 105, 120, 15, 15, 15, 15]","[15, 219, 75, 30, 105, 30, 15, 90, 0]","[210, 9, 30, 30, 0]"
19,"[180, 66, 258]","[135, 15, 75, 30, 45, 45, 30, 60, 3]","[120, 141, 30, 15, 30, 15, 30, 30, 15, 45, 30,...","[30, 30, 15, 78]"
20,"[150, 30, 60, 15, 15, 30, 30, 30, 21]","[75, 30, 30, 15, 45, 81]","[45, 15, 96]","[60, 15, 30, 30, 6]"
21,"[210, 43, 15, 30, 11]","[120, 163, 15, 45, 15, 15, 15, 71]","[180, 58, 90, 45, 30, 75, 45, 56]","[45, 15, 30, 15, 71]"
22,"[135, 170, 15, 30, 4]","[0, 350, 15, 15, 15, 15, 60, 15, 94]","[75, 170, 165, 15, 90, 64]","[75, 15, 15, 30, 30, 15, 19]"
23,"[30, 240, 90, 15, 165, 15, 15, 9]","[180, 60, 15, 60, 15, 15, 84]","[0, 300, 60, 45, 15, 30, 90, 39]","[105, 15, 30, 30, 69]"
24,"[45, 338, 75, 30, 15, 15, 61]","[60, 105, 45, 30, 46]","[105, 30, 15, 30, 15, 15, 15, 30, 46]","[0, 15, 30, 30, 30, 15, 16]"
25,"[45, 15, 60, 30, 30, 30, 15, 38]","[30, 75, 60, 15, 8]","[180, 46, 15, 60, 15, 45, 90, 15, 75, 15, 23]","[15, 15, 30, 15, 30, 15, 8]"
26,"[60, 60, 15, 30, 12]","[195, 57, 15, 30, 15, 75, 72]","[150, 132, 15, 30, 135, 117]","[45, 192, 75, 30, 60, 135, 42]"
27,"[75, 30, 30, 30, 15, 15, 150, 69]","[15, 15, 60, 30, 30, 120, 39]","[135, 15, 15, 30, 15, 15, 30, 15, 24]","[180, 60, 15, 15, 45, 60, 75, 45, 30, 54]"
28,"[210, 33, 30, 30, 105, 30, 66]","[90, 228, 15, 60, 15, 30, 6]","[105, 168, 15, 90, 15, 105, 45, 15, 15, 6]","[90, 153, 15, 30, 30, 30, 75, 75, 30, 51]"
29,"[45, 192, 45, 30, 30, 30, 15, 15, 30, 12]","[210, 12, 15, 30, 15, 15, 12]","[90, 177, 120, 15, 120, 57]","[180, 42, 195, 60, 60, 42]"
30,"[60, 15, 15, 90, 80]","[150, 15, 15, 60, 105, 15, 15, 35]","[90, 139, 15, 30, 90, 15, 45, 150, 5]","[75, 15, 15, 30, 15, 15, 20]"
...,...,...,...,...
971,"[90, 127, 15, 15, 105, 30, 15, 15, 15, 32]","[135, 97, 30, 15, 45, 90, 62]","[75, 30, 30, 77]","[135, 127, 45, 30, 30, 75, 135, 2]"
972,"[120, 180, 60, 0]","[0, 15, 15, 15, 15, 30, 15, 15]","[105, 15, 30, 15, 15, 75, 0]","[45, 234, 150, 30, 15, 60, 45]"
973,"[210, 71, 90, 15, 30, 15, 30, 15, 103]","[45, 221, 90, 120, 13]","[0, 236, 15, 60, 15, 15, 15, 15, 30, 30, 15, 4...","[120, 15, 30, 30, 30, 15, 13]"
974,"[195, 107, 15, 15, 15, 30, 30, 22]","[180, 15, 15, 157]","[90, 15, 15, 15, 30, 15, 7]","[120, 137, 15, 45, 15, 15, 90, 15, 45, 15, 15,..."
975,"[210, 12, 30, 45, 15, 30, 15, 15, 12]","[105, 147, 15, 15, 15, 45, 42]","[210, 12, 15, 30, 75, 15, 15, 150, 57]","[90, 30, 15, 12]"
976,"[60, 315, 15, 39]","[0, 225, 75, 30, 15, 9]","[45, 30, 30, 30, 15, 30, 84]","[180, 45, 75, 45, 75, 45, 15, 30, 45, 24]"
977,"[75, 60, 15, 15, 89]","[75, 385, 15, 15, 15, 44]","[45, 30, 30, 15, 14]","[15, 235, 15, 30, 45, 15, 30, 15, 15, 15, 15, ..."
978,"[180, 83, 30, 45, 30, 15, 30, 105, 15, 15, 15,...","[60, 173, 15, 30, 105, 75, 1]","[120, 143, 30, 30, 15, 90, 60, 91]","[90, 30, 15, 15, 15, 30, 30, 30, 16]"
979,"[195, 47, 45, 15, 75, 15, 30, 7]","[45, 272, 15, 15, 15, 30, 82]","[180, 77, 15, 30, 75, 45, 60, 60, 15, 22]","[135, 92, 105, 240, 7]"
980,"[105, 120]","[75, 120, 15, 30, 15, 45, 0]","[195, 15, 30, 15, 225]","[60, 159, 15, 30, 15, 105, 105, 75, 15]"
981,"[45, 15, 15, 30, 60, 4]","[120, 95, 15, 45, 75, 45, 15, 15, 15, 34]","[15, 320, 15, 15, 30, 90, 15, 45, 15, 19]","[210, 80, 30, 60, 60, 30, 30, 75, 4]"
982,"[210, 15, 30, 30, 30, 15]","[105, 249, 15, 15, 30, 105, 60]","[180, 84, 135, 15, 30, 15, 15, 75, 30]","[30, 204, 105, 150, 15, 60, 15]"
983,"[30, 30, 15, 30, 75, 15, 30, 90, 30, 21]","[150, 15, 15, 15, 36]","[75, 258, 45, 30, 30, 15, 45, 15, 15, 15, 15, 21]","[0, 30, 30, 30, 30, 6]"
984,"[135, 30, 60, 15, 15, 30, 15, 15, 102]","[60, 30, 60, 15, 30, 42]","[150, 72, 15, 75, 165, 102]","[0, 252, 120, 45, 15, 90, 30, 15, 12]"
985,"[60, 300, 15, 30, 15, 15, 15, 9]","[210, 30, 60, 54]","[105, 39]","[15, 240, 30, 15, 45, 60, 90, 30, 45, 9]"
986,"[75, 15, 30, 30, 30, 15, 30, 15, 15, 15, 30, 29]","[120, 145, 15, 30, 30, 60, 44]","[210, 70, 15, 60, 45, 60, 105, 14]","[90, 15, 30, 164]"
987,"[150, 124, 30, 60, 15, 30, 60, 60, 30, 20]","[15, 379, 15, 15, 45, 35]","[90, 30, 15, 15, 15, 20]","[30, 30, 15, 15, 35]"
988,"[45, 219, 15, 30, 60, 15, 60, 15, 45]","[60, 15, 15, 15, 15, 15, 120, 15, 0]","[30, 249, 105, 15, 15, 15, 30, 45, 30, 45]","[75, 174, 15, 60, 165, 60, 30, 0]"
989,"[135, 210, 15, 30, 30, 15, 2]","[0, 247, 150, 32]","[210, 7, 15, 60, 15, 75, 90, 15, 30, 30, 32]","[90, 15, 30, 15, 2]"
990,"[120, 94, 15, 45, 60, 15, 15, 30, 30, 5]","[90, 45, 60, 45, 60, 15, 50]","[165, 94, 30, 30, 60, 15, 30, 15, 15, 15, 75, ...","[75, 15, 30, 5]"
991,"[165, 50, 15, 15, 30, 45, 15, 45, 15, 15, 15, ...","[135, 110, 15, 105, 60, 4]","[30, 230, 15, 45, 135, 90, 34]","[15, 230, 15, 120, 45, 60, 75, 15, 4]"
992,"[120, 24]","[30, 75, 30, 15, 15, 30, 9]","[150, 90, 15, 15, 15, 30, 15, 15, 60, 30, 15, ...","[135, 105, 15, 15, 30, 75, 15, 15, 45, 15, 45,..."
993,"[165, 72, 60, 30, 15, 15, 12]","[135, 387, 57]","[15, 15, 15, 30, 30, 15, 30, 15, 27]","[0, 267, 15, 45, 15, 75, 60, 15, 15, 72]"
994,"[120, 120, 45, 120, 54]","[90, 165, 15, 15, 15, 135, 69]","[75, 150, 45, 45, 60, 60, 15, 45, 45, 15, 15, 9]","[210, 30, 15, 30, 15, 15, 24]"
995,"[210, 39, 30, 30, 30, 15]","[60, 159, 15, 45, 105, 150]","[150, 69, 30, 15, 45, 45, 15, 75, 75, 15, 45]","[30, 294, 15, 60, 15, 75, 15, 45, 30, 0]"
996,"[90, 162, 45, 45, 30, 30, 60, 30, 27]","[120, 117, 15, 57]","[75, 15, 30, 30, 30, 15, 30, 30, 117]","[15, 30, 12]"
997,"[90, 215, 15, 75, 15, 30, 15, 45, 79]","[60, 170, 60, 45, 90, 4]","[120, 30, 19]","[75, 200, 15, 15, 15, 45, 45, 15, 30, 60, 30, 34]"
998,"[45, 186, 15, 15, 30, 15, 60, 15, 60, 45, 15, ...","[90, 201, 45, 3]","[150, 30, 15, 30, 15, 108]","[180, 30, 15, 15, 30, 30, 15, 15, 15, 30, 18]"
999,"[60, 15, 15, 30, 25]","[30, 15, 15, 45, 10]","[105, 134, 30, 30, 15, 15, 90, 30, 130]","[165, 59, 120, 30, 30, 15, 15, 45, 30, 30, 30,..."
1000,"[75, 348, 15, 15, 15, 15, 30, 15, 6]","[150, 108, 30, 15, 15, 15, 15, 15, 111]","[30, 303, 45, 15, 45, 15, 120, 6]","[180, 276]"

In [12]:
comp_times_frame

,comp1,comp2,comp3,comp4
1,"[60, 210]","[248, 30]","[83, 60, 60]","[278, 60, 45, 75, 45]"
2,"[45, 60, 45]","[80, 60, 60]",[],[]
3,"[220, 75]","[265, 45]",[],[]
4,[120],"[179, 45, 45, 30, 30]",[],[]
5,[45],"[30, 30, 30]","[279, 45, 120, 60]",[]
6,[75],[],[],[]
7,"[140, 75, 45]","[80, 75, 30, 30, 45, 30]",[],"[215, 165]"
8,"[67, 105]","[187, 75, 105, 30]",[],"[67, 60, 105]"
9,"[45, 75]","[30, 30]","[166, 45, 60, 60, 90]",[]
10,"[93, 75]","[45, 60, 30]","[78, 60, 60, 45]",[]
11,"[208, 45]","[358, 60]",[],[]
12,"[136, 60]","[60, 30]","[151, 135, 120]",[]
13,[],"[90, 45]",[],"[150, 75, 45, 60, 60]"
14,[248],[158],[],[]
15,"[217, 60]",[],[],"[247, 45, 90, 90, 45]"
16,"[89, 90]","[60, 30]",[],[]
17,[],"[131, 60, 75, 30, 45]",[],"[191, 45, 60, 60]"
18,[180],[30],[],"[120, 45, 135]"
19,[75],"[96, 45]",[],"[186, 60, 45, 75, 60]"
20,"[93, 105]","[183, 30, 90]","[258, 105, 60]","[243, 60, 60, 75]"
21,"[90, 105, 75]","[45, 75]",[],"[268, 90, 45]"
22,"[120, 105]",[],[],"[170, 45, 120, 45]"
23,[],"[30, 45, 45, 30]",[],"[135, 60, 45, 45, 45]"
24,[],"[173, 120]","[143, 75, 60]","[263, 120, 60]"
25,"[211, 105]","[196, 75, 30, 45, 45]",[],"[256, 105, 45, 45]"
26,"[252, 45, 60, 45]","[60, 30, 30]",[],[]
27,[165],"[210, 60]","[120, 165]",[]
28,[75],[135],[],[]
29,"[90, 45]","[30, 60, 45, 75, 60]",[],[]
30,"[259, 60]","[109, 60]",[],"[154, 135, 45, 60]"
...,...,...,...,...
971,"[60, 60]","[75, 30]","[247, 120]",[]
972,"[114, 105]","[219, 45, 60, 30, 45, 60]","[144, 180]",[]
973,[],"[30, 60]",[],"[101, 90, 45, 90]"
974,"[90, 60]","[62, 30, 75, 45]","[197, 45, 150]",[]
975,"[75, 120]","[45, 60, 30, 60]",[],"[177, 255]"
976,"[60, 90]","[180, 45]","[210, 45, 60]",[]
977,"[235, 90]",[30],"[250, 60, 135]",[]
978,[],[120],[],"[128, 60, 120]"
979,"[60, 45, 45]",[105],[],[]
980,"[219, 45, 90]","[174, 45, 60]",[99],[]
981,"[200, 135, 75]","[30, 75]",[],[]
982,"[69, 90, 90]",[],[],[]
983,[213],"[93, 45, 75, 90, 45]",[],"[258, 45, 60, 90]"
984,"[117, 45]","[177, 30, 45, 45, 45]",[],[]
985,[120],"[60, 30, 45, 45, 45]","[210, 45, 180]",[]
986,[250],"[30, 105]",[],"[145, 45, 90]"
987,[],[75],"[154, 60, 75, 60, 45]","[259, 90, 105]"
988,[75],"[159, 60, 90]",[],[]
989,"[82, 60]","[45, 75, 30]",[],"[172, 45, 90, 120]"
990,[150],"[184, 30]",[],"[169, 45, 60, 90, 90]"
991,"[60, 45]","[45, 105]",[],[]
992,"[225, 210]","[270, 45, 60]",[],[]
993,"[135, 75]",[],"[222, 45, 45, 75]",[]
994,"[45, 75]","[45, 30]",[],"[105, 75, 60]"
995,"[105, 120]",[45],[],[]
996,[60],"[30, 60, 45, 135]","[162, 45]","[417, 45, 60]"
997,[],"[45, 105]","[125, 105, 45, 75, 60]",[]
998,[45],"[30, 75, 105, 30]","[66, 60, 60, 45]","[51, 45, 45, 45]"
999,"[239, 90, 45, 60]","[194, 30, 30, 75, 135]",[],[]
1000,[45],"[45, 60]",[],"[63, 60]"

In [9]:
maint

                 datetime  machineID   comp  IF_FAIL
0     2014-07-01 06:00:00          1  comp4        0
1     2014-09-14 06:00:00          1  comp1        0
2     2014-09-14 06:00:00          1  comp2        0
3     2014-11-13 06:00:00          1  comp3        0
4     2015-01-05 06:00:00          1  comp1        0
5     2015-01-20 06:00:00          1  comp1        0
6     2015-02-04 06:00:00          1  comp3        1
7     2015-02-19 06:00:00          1  comp3        0
8     2015-03-06 06:00:00          1  comp3        0
9     2015-03-21 06:00:00          1  comp1        1
10    2015-04-05 06:00:00          1  comp1        0
11    2015-04-05 06:00:00          1  comp4        1
12    2015-04-20 06:00:00          1  comp1        0
13    2015-05-05 06:00:00          1  comp3        1
14    2015-05-20 06:00:00          1  comp2        1
15    2015-06-04 06:00:00          1  comp4        1
16    2015-06-04 06:00:00          1  comp3        0
17    2015-06-19 06:00:00          1  comp2        1
18    2015-06-19 06:00:00          1  comp4        0
19    2015-07-04 06:00:00          1  comp2        0
20    2015-07-19 06:00:00          1  comp2        0
21    2015-08-03 06:00:00          1  comp4        1
22    2015-08-03 06:00:00          1  comp3        1
23    2015-08-18 06:00:00          1  comp4        0
24    2015-09-02 06:00:00          1  comp3        0
25    2015-09-17 06:00:00          1  comp3        0
26    2015-10-17 06:00:00          1  comp3        0
27    2015-10-17 06:00:00          1  comp2        0
28    2015-11-01 06:00:00          1  comp4        1
29    2015-11-16 06:00:00          1  comp1        1
...                   ...        ...    ...      ...
32562 2015-12-22 06:00:00        999  comp4        0
32563 2014-07-01 06:00:00       1000  comp3        0
32564 2014-08-15 06:00:00       1000  comp1        0
32565 2014-10-29 06:00:00       1000  comp2        0
32566 2014-11-28 06:00:00       1000  comp4        0
32567 2015-01-30 06:00:00       1000  comp4        1
32568 2015-02-14 06:00:00       1000  comp2        0
32569 2015-03-16 06:00:00       1000  comp2        0
32570 2015-03-31 06:00:00       1000  comp2        0
32571 2015-03-31 06:00:00       1000  comp4        1
32572 2015-04-30 06:00:00       1000  comp3        0
32573 2015-05-15 06:00:00       1000  comp2        1
32574 2015-05-30 06:00:00       1000  comp2        0
32575 2015-06-14 06:00:00       1000  comp2        0
32576 2015-06-14 06:00:00       1000  comp3        0
32577 2015-06-29 06:00:00       1000  comp3        0
32578 2015-07-29 06:00:00       1000  comp1        0
32579 2015-08-13 06:00:00       1000  comp2        1
32580 2015-08-13 06:00:00       1000  comp3        0
32581 2015-08-28 06:00:00       1000  comp3        0
32582 2015-08-28 06:00:00       1000  comp2        0
32583 2015-09-12 06:00:00       1000  comp2        0
32584 2015-09-12 06:00:00       1000  comp1        1
32585 2015-09-27 06:00:00       1000  comp1        0
32586 2015-10-12 06:00:00       1000  comp1        0
32587 2015-10-27 06:00:00       1000  comp1        0
32588 2015-11-11 06:00:00       1000  comp1        0
32589 2015-12-11 06:00:00       1000  comp1        0
32590 2015-12-26 06:00:00       1000  comp3        0
32591 2015-12-26 06:00:00       1000  comp1        0

[32592 rows x 4 columns]